const TransactionActionTypes = {
    FETCH_NFT_TRANSACTION_START: 'FETCH_NFT_TRANSACTION_START',
    FETCH_NFT_TRANSACTION_SUCCESS: 'FETCH_NFT_TRANSACTION_SUCCESS',
    FETCH_NFT_TRANSACTION_FAILURE: 'FETCH_NFT_TRANSACTION_FAILURE',
    FETCH_PAYMENT_TRANSACTION_START: 'FETCH_PAYMENT_TRANSACTION_START',
    FETCH_PAYMENT_TRANSACTION_SUCCESS: 'FETCH_PAYMENT_TRANSACTION_SUCCESS',
    FETCH_PAYMENT_TRANSACTION_FAILURE: 'FETCH_PAYMENT_TRANSACTION_FAILURE',
	TOGGLE_BUYING: 'TOGGLE_BUYING'
};

export default TransactionActionTypes;



