const UserActionTypes = {
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SIGN_OUT: 'SIGN_OUT',
	SET_BALANCE: 'SET_BALANCE',
	SET_ETHEREUM: 'SET_ETHEREUM',
	SET_VOLUME: 'SET_VOLUME'
};

export default UserActionTypes;


